"""Add anonymity flag to topics and posts

Revision ID: 319399a41239
Revises: 2e8be295db25
Create Date: 2024-06-15 23:39:10.679136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319399a41239'
down_revision = '2e8be295db25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')

    op.create_table('demo',
    sa.Column('ID', sa.INTEGER(), nullable=True),
    sa.Column('Name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('Hint', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###
