"""Add attendance table

Revision ID: 62d2520f32bf
Revises: 319399a41239
Create Date: 2024-06-16 08:09:33.971471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d2520f32bf'
down_revision = '319399a41239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('demo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo',
    sa.Column('ID', sa.INTEGER(), nullable=True),
    sa.Column('Name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('Hint', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('attendance')
    # ### end Alembic commands ###
